name: gpu-tests

on:
  pull_request:
  push:
    branches: main

jobs:
  test-linux:
    runs-on: [self-hosted, linux]
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
        pip install -e .
        pip install pytest
    - name: Test with pytest
      run: |
        pytest
